export const homeObjTwo = {
  lightBg: true,
  primary: true,
  buttonFontBig: false,
  buttonBig: false,
  imgStart: true,
  lightTopLine: false,
  lightTextDesc: false,
  lightText: false,
  bigText: false,
  bigSubText: false,
  buttonLabel: "Više o nama",
  desc:
    "Naš se tim sastoji od mladih profesionalaca, dizajnera i programera sa strašću za tehnologijom, kreativnom dizjanu i modernim idejama sa petogodišnjim iskustvom. Locirani smo u Bihaću - Bosna i Hercegovina i nudimo klijentima razne vrste usluga - web i grafički dizajn, razvoj i izrada web stranica, mobilne aplikacije, e-commerce i više.",
  headline: "Šta Je Sky Media?",
  topLine: "O Nama",
  img: require("../../assets/images/about/aboutus.json"),
  alt: "Landing page image.",
  noMobile: false,
  start: "",
  small: true,
};
