export const homeObjOne = {
  lightBg: false,
  primary: true,
  buttonFontBig: true,
  buttonBig: true,
  imgStart: false,
  lightTopLine: true,
  lightTextDesc: true,
  lightText: true,
  bigText: true,
  bigSubText: true,
  buttonLabel: "home.buttonOne",
  desc: "home.subline",
  headline: "home.heading",
  topLine: "home.topline",
  img: require("../../assets/images/home/slider1.json"),
  alt: "Landing page image.",
  noMobile: true,
  start: "",
  small: true,
  relative: true,
  bigPadding: false,
  infoBoxDisplay: true,
  noDisplay: true,
  container: true,
  noShowReel: false,
};

export const homeObjTwo = {
  lightBg: true,
  primary: true,
  buttonFontBig: false,
  buttonBig: false,
  imgStart: true,
  lightTopLine: true,
  lightTextDesc: false,
  lightText: false,
  bigText: false,
  bigSubText: false,
  buttonLabel: "homeAbout.buttonOne",
  desc: "homeAbout.subline",
  headline: "homeAbout.heading",
  topLine: "homeAbout.topline",
  img: require("../../assets/images/home/lottieSeven.json"),
  alt: "Landing page image.",
  noMobile: false,
  start: "",
  small: true,
  relative: false,
  bigPadding: true,
  infoBoxDisplay: false,
  noDisplay: false,
  noShowReel: true,
};

export const homeObjThree = {
  goldTitle: true,
  whiteTitle: true,
};

export const homeObjFour = {
  goldTitle: true,
  whiteTitle: false,
  primary: true,
  buttonFontBig: false,
  buttonBig: false,
};
